name: CI Code Check & Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest

      - name: Lint code with Flake8
        run: |
          # Stop build if there are syntax errors or undefined names
          flake8 src/ main.py --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Pytest
        run: |
          # Executes tests if you have a tests/ directory
          pytest --ignore=quant_env